/********************************************************************
* Dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary();
extern void G__cpp_setup_inheritanceDictionary();
extern void G__cpp_setup_typetableDictionary();
extern void G__cpp_setup_memvarDictionary();
extern void G__cpp_setup_globalDictionary();
extern void G__cpp_setup_memfuncDictionary();
extern void G__cpp_setup_funcDictionary();
extern void G__set_cpp_environmentDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AliAnalysisTaskDiffCrossSectionsMM.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictionaryLN_TClass;
extern G__linked_taginfo G__DictionaryLN_TBuffer;
extern G__linked_taginfo G__DictionaryLN_TMemberInspector;
extern G__linked_taginfo G__DictionaryLN_TObject;
extern G__linked_taginfo G__DictionaryLN_TNamed;
extern G__linked_taginfo G__DictionaryLN_TString;
extern G__linked_taginfo G__DictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictionaryLN_TTree;
extern G__linked_taginfo G__DictionaryLN_AliMCEvent;
extern G__linked_taginfo G__DictionaryLN_AliESDEvent;
extern G__linked_taginfo G__DictionaryLN_TBits;
extern G__linked_taginfo G__DictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DictionaryLN_TLorentzVector;
extern G__linked_taginfo G__DictionaryLN_TParticle;
extern G__linked_taginfo G__DictionaryLN_AliStack;
extern G__linked_taginfo G__DictionaryLN_AliESDVertex;
extern G__linked_taginfo G__DictionaryLN_TTask;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTask;
extern G__linked_taginfo G__DictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskSE;
extern G__linked_taginfo G__DictionaryLN_AliTriggerAnalysis;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisUtils;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMM;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLEventInfo;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLADV0;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLADV0cLcLdA;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLZDC;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLZDCcLcLdA;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLVtxInfo;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLTreeData;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLMCInfo;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLMCInfocLcLdA;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLMCInfocLcLDetGenLevel;
extern G__linked_taginfo G__DictionaryLN_AliAnalysisTaskDiffCrossSectionsMMcLcLMCInfocLcLDiffSystem;

/* STUB derived class for protected member access */
